export const ENV = {
  FIREBASE: {
    API_KEY: process.env.EXPO_PUBLIC_FIREBASE_API_KEY!,
    AUTH_DOMAIN: process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN!,
    PROJECT_ID: process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID!,
    STORAGE_BUCKET: process.env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET!,
    MESSAGING_SENDER_ID: process.env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID!,
    APP_ID: process.env.EXPO_PUBLIC_FIREBASE_APP_ID!,
  },

  GOOGLE: {
    WEB_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID!,
  },

  APP_ENV: process.env.EXPO_PUBLIC_APP_ENV ?? 'development',
};
